//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoTankYou.Localization {
    using global::System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoTankYou.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Icon.
        /// </summary>
        internal static string ActionIcon {
            get {
                return ResourceManager.GetString("ActionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        internal static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Spacing.
        /// </summary>
        internal static string AdditionalSpacing {
            get {
                return ResourceManager.GetString("AdditionalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing Effects.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing Period (milliseconds).
        /// </summary>
        internal static string AnimationPeriod {
            get {
                return ResourceManager.GetString("AnimationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Overlay.
        /// </summary>
        internal static string BannerOverlay {
            get {
                return ResourceManager.GetString("BannerOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        internal static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklisted Zones.
        /// </summary>
        internal static string BlacklistedZones {
            get {
                return ResourceManager.GetString("BlacklistedZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Mage.
        /// </summary>
        internal static string BlueMage {
            get {
                return ResourceManager.GetString("BlueMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botanist.
        /// </summary>
        internal static string Botanist {
            get {
                return ResourceManager.GetString("Botanist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff Count.
        /// </summary>
        internal static string BuffCount {
            get {
                return ResourceManager.GetString("BuffCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Alliance Tanks.
        /// </summary>
        internal static string CheckAllianceTanks {
            get {
                return ResourceManager.GetString("CheckAllianceTanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate warnings if none of the tanks in any any alliance have their stance on.
        /// </summary>
        internal static string CheckAllianceTanksHelp {
            get {
                return ResourceManager.GetString("CheckAllianceTanksHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocobo.
        /// </summary>
        internal static string Chocobo {
            get {
                return ResourceManager.GetString("Chocobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocobo Missing.
        /// </summary>
        internal static string ChocoboMissing {
            get {
                return ResourceManager.GetString("ChocoboMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectors Glove.
        /// </summary>
        internal static string CollectorsGlove {
            get {
                return ResourceManager.GetString("CollectorsGlove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterion.
        /// </summary>
        internal static string Criterion {
            get {
                return ResourceManager.GetString("Criterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Label.
        /// </summary>
        internal static string CustomWarning {
            get {
                return ResourceManager.GetString("CustomWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Text.
        /// </summary>
        internal static string CustomWarningText {
            get {
                return ResourceManager.GetString("CustomWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Partner.
        /// </summary>
        internal static string DancePartner {
            get {
                return ResourceManager.GetString("DancePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancer.
        /// </summary>
        internal static string Dancer {
            get {
                return ResourceManager.GetString("Dancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable in Alliance Raid.
        /// </summary>
        internal static string DisableInAllianceRaid {
            get {
                return ResourceManager.GetString("DisableInAllianceRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents generating any warnings while in an Alliance Raid..
        /// </summary>
        internal static string DisableInAllianceRaidHelp {
            get {
                return ResourceManager.GetString("DisableInAllianceRaidHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Module.
        /// </summary>
        internal static string DisableModuleHelp {
            get {
                return ResourceManager.GetString("DisableModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling.
        /// </summary>
        internal static string Disabling {
            get {
                return ResourceManager.GetString("Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Colors.
        /// </summary>
        internal static string DisplayColors {
            get {
                return ResourceManager.GetString("DisplayColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        internal static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List shows multiple warnings at the same time, up to the specified max warnings
        ///Top Priority will only show one warning at a time.
        /// </summary>
        internal static string DisplayModeHelp {
            get {
                return ResourceManager.GetString("DisplayModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Options.
        /// </summary>
        internal static string DisplayOptions {
            get {
                return ResourceManager.GetString("DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Style.
        /// </summary>
        internal static string DisplayStyle {
            get {
                return ResourceManager.GetString("DisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duties Only.
        /// </summary>
        internal static string DutiesOnly {
            get {
                return ResourceManager.GetString("DutiesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only generate warnings while in a duty.
        /// </summary>
        internal static string DutiesOnlyHelp {
            get {
                return ResourceManager.GetString("DutiesOnlyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Early Warning.
        /// </summary>
        internal static string EarlyWarning {
            get {
                return ResourceManager.GetString("EarlyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Warning Time (seconds).
        /// </summary>
        internal static string EarlyWarningTime {
            get {
                return ResourceManager.GetString("EarlyWarningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Module.
        /// </summary>
        internal static string EnableModuleHelp {
            get {
                return ResourceManager.GetString("EnableModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Zone Filter.
        /// </summary>
        internal static string EnableZoneFilter {
            get {
                return ResourceManager.GetString("EnableZoneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling.
        /// </summary>
        internal static string Enabling {
            get {
                return ResourceManager.GetString("Enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme &amp; Unreal.
        /// </summary>
        internal static string ExtremeUnreal {
            get {
                return ResourceManager.GetString("ExtremeUnreal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Buff.
        /// </summary>
        internal static string FirstBuff {
            get {
                return ResourceManager.GetString("FirstBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisher.
        /// </summary>
        internal static string Fisher {
            get {
                return ResourceManager.GetString("Fisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Missing.
        /// </summary>
        internal static string FoodWarning {
            get {
                return ResourceManager.GetString("FoodWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company.
        /// </summary>
        internal static string FreeCompany {
            get {
                return ResourceManager.GetString("FreeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company Buff.
        /// </summary>
        internal static string FreeCompanyBuff {
            get {
                return ResourceManager.GetString("FreeCompanyBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Generate warnings if you do not have the &quot;First Buff&quot;
        ///2 - Generate warnings if you do not have the &quot;First Buff&quot; and &quot;Second Buff&quot;.
        /// </summary>
        internal static string FreeCompanyBuffCountHelp {
            get {
                return ResourceManager.GetString("FreeCompanyBuffCountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any - Generate warnings if you do not have any Free Company Buffs
        ///Specific - Generate warnings if you do not have the specified Free Company Buffs.
        /// </summary>
        internal static string FreeCompanyModeHelp {
            get {
                return ResourceManager.GetString("FreeCompanyModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatherers.
        /// </summary>
        internal static string Gatherers {
            get {
                return ResourceManager.GetString("Gatherers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Options.
        /// </summary>
        internal static string GeneralOptions {
            get {
                return ResourceManager.GetString("GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this help message.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Sanctuaries.
        /// </summary>
        internal static string HideInSanctuary {
            get {
                return ResourceManager.GetString("HideInSanctuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show warnings in towns or outposts.
        /// </summary>
        internal static string HideInSanctuaryHelp {
            get {
                return ResourceManager.GetString("HideInSanctuaryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Icon.
        /// </summary>
        internal static string JobIcon {
            get {
                return ResourceManager.GetString("JobIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Based Warnings.
        /// </summary>
        internal static string JobWarnings {
            get {
                return ResourceManager.GetString("JobWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Warnings.
        /// </summary>
        internal static string MaxWarnings {
            get {
                return ResourceManager.GetString("MaxWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mighty Guard.
        /// </summary>
        internal static string MightyGuard {
            get {
                return ResourceManager.GetString("MightyGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miner.
        /// </summary>
        internal static string Miner {
            get {
                return ResourceManager.GetString("Miner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Select.
        /// </summary>
        internal static string ModeSelect {
            get {
                return ResourceManager.GetString("ModeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Blacklist.
        /// </summary>
        internal static string ModuleBlacklist {
            get {
                return ResourceManager.GetString("ModuleBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to prevent warnings from selected modules from appearing..
        /// </summary>
        internal static string ModuleBlacklistInfo {
            get {
                return ResourceManager.GetString("ModuleBlacklistInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Options.
        /// </summary>
        internal static string ModuleOptions {
            get {
                return ResourceManager.GetString("ModuleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Blacklisted.
        /// </summary>
        internal static string NothingBlacklisted {
            get {
                return ResourceManager.GetString("NothingBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration Window.
        /// </summary>
        internal static string OpenConfigWindow {
            get {
                return ResourceManager.GetString("OpenConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Color.
        /// </summary>
        internal static string OutlineColor {
            get {
                return ResourceManager.GetString("OutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Names.
        /// </summary>
        internal static string PlayerNames {
            get {
                return ResourceManager.GetString("PlayerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positioning.
        /// </summary>
        internal static string Positioning {
            get {
                return ResourceManager.GetString("Positioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the order that warnings will appear if multiple warnings are generated.
        /// </summary>
        internal static string PriorityHelp {
            get {
                return ResourceManager.GetString("PriorityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage.
        /// </summary>
        internal static string Sage {
            get {
                return ResourceManager.GetString("Sage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage Kardion.
        /// </summary>
        internal static string SageKardion {
            get {
                return ResourceManager.GetString("SageKardion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Mode.
        /// </summary>
        internal static string SampleMode {
            get {
                return ResourceManager.GetString("SampleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savage.
        /// </summary>
        internal static string Savage {
            get {
                return ResourceManager.GetString("Savage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        internal static string Scholar {
            get {
                return ResourceManager.GetString("Scholar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar Faerie.
        /// </summary>
        internal static string ScholarFaerie {
            get {
                return ResourceManager.GetString("ScholarFaerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Buff.
        /// </summary>
        internal static string SecondBuff {
            get {
                return ResourceManager.GetString("SecondBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Time Remaining.
        /// </summary>
        internal static string ShowTimeRemaining {
            get {
                return ResourceManager.GetString("ShowTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Mode.
        /// </summary>
        internal static string SoloMode {
            get {
                return ResourceManager.GetString("SoloMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only generate warnings for you.
        /// </summary>
        internal static string SoloModeHelp {
            get {
                return ResourceManager.GetString("SoloModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific.
        /// </summary>
        internal static string Specific {
            get {
                return ResourceManager.GetString("Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritbond.
        /// </summary>
        internal static string SpiritBond {
            get {
                return ResourceManager.GetString("SpiritBond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritbond Missing.
        /// </summary>
        internal static string SpiritBondWarning {
            get {
                return ResourceManager.GetString("SpiritBondWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoH Status Missing.
        /// </summary>
        internal static string StatusMissing {
            get {
                return ResourceManager.GetString("StatusMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner.
        /// </summary>
        internal static string Summoner {
            get {
                return ResourceManager.GetString("Summoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner Pet.
        /// </summary>
        internal static string SummonerPet {
            get {
                return ResourceManager.GetString("SummonerPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress in Combat.
        /// </summary>
        internal static string SuppressInCombat {
            get {
                return ResourceManager.GetString("SuppressInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressing {0} Warnings for: {1}.
        /// </summary>
        internal static string SuppressingWarnings {
            get {
                return ResourceManager.GetString("SuppressingWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress current warnings from players for this module until next zone change.
        /// </summary>
        internal static string SuppressModuleHelp {
            get {
                return ResourceManager.GetString("SuppressModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        internal static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Stance.
        /// </summary>
        internal static string TankStance {
            get {
                return ResourceManager.GetString("TankStance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Module.
        /// </summary>
        internal static string ToggleModuleHelp {
            get {
                return ResourceManager.GetString("ToggleModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Priority.
        /// </summary>
        internal static string TopPriority {
            get {
                return ResourceManager.GetString("TopPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate.
        /// </summary>
        internal static string Ultimate {
            get {
                return ResourceManager.GetString("Ultimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait For Duty Start.
        /// </summary>
        internal static string WaitForDutyStart {
            get {
                return ResourceManager.GetString("WaitForDutyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents warnings from showing until &quot;Duty Commenced&quot; appears.
        /// </summary>
        internal static string WaitForDutyStartHelp {
            get {
                return ResourceManager.GetString("WaitForDutyStartHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Shield.
        /// </summary>
        internal static string WarningShield {
            get {
                return ResourceManager.GetString("WarningShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Text.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Window Dragging.
        /// </summary>
        internal static string WindowDragging {
            get {
                return ResourceManager.GetString("WindowDragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Dragging Enabled.
        /// </summary>
        internal static string WindowDraggingEnabled {
            get {
                return ResourceManager.GetString("WindowDraggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Filter.
        /// </summary>
        internal static string ZoneFilter {
            get {
                return ResourceManager.GetString("ZoneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate warnings only in enabled zones.
        /// </summary>
        internal static string ZoneFilterDescription {
            get {
                return ResourceManager.GetString("ZoneFilterDescription", resourceCulture);
            }
        }
    }
}
