//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoTankYou.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoTankYou.System.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Thickness.
        /// </summary>
        internal static string BannerOverlay_BorderThickness {
            get {
                return ResourceManager.GetString("BannerOverlay_BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Overlay Configuration.
        /// </summary>
        internal static string BannerOverlay_ConfigurationLabel {
            get {
                return ResourceManager.GetString("BannerOverlay_ConfigurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Exclamation Mark.
        /// </summary>
        internal static string BannerOverlay_ExclamationMark {
            get {
                return ResourceManager.GetString("BannerOverlay_ExclamationMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icon.
        /// </summary>
        internal static string BannerOverlay_Icon {
            get {
                return ResourceManager.GetString("BannerOverlay_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icon Text.
        /// </summary>
        internal static string BannerOverlay_IconText {
            get {
                return ResourceManager.GetString("BannerOverlay_IconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Overlay.
        /// </summary>
        internal static string BannerOverlay_Label {
            get {
                return ResourceManager.GetString("BannerOverlay_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string BannerOverlay_ListMode {
            get {
                return ResourceManager.GetString("BannerOverlay_ListMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays warnings from multiple party members at the same time.
        /// </summary>
        internal static string BannerOverlay_ListModeDescription {
            get {
                return ResourceManager.GetString("BannerOverlay_ListModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Mode Options.
        /// </summary>
        internal static string BannerOverlay_ListModeOptions {
            get {
                return ResourceManager.GetString("BannerOverlay_ListModeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Player Names.
        /// </summary>
        internal static string BannerOverlay_PlayerNames {
            get {
                return ResourceManager.GetString("BannerOverlay_PlayerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Mode - Allows repositioning.
        /// </summary>
        internal static string BannerOverlay_RepositionMode {
            get {
                return ResourceManager.GetString("BannerOverlay_RepositionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Mode.
        /// </summary>
        internal static string BannerOverlay_SoloMode {
            get {
                return ResourceManager.GetString("BannerOverlay_SoloMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only display Warnings that are generated by you.
        /// </summary>
        internal static string BannerOverlay_SoloModeHelp {
            get {
                return ResourceManager.GetString("BannerOverlay_SoloModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display only one warning at a time.
        /// </summary>
        internal static string BannerOverlay_TopPriorityDescription {
            get {
                return ResourceManager.GetString("BannerOverlay_TopPriorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string BannerOverlay_TopPriorityMode {
            get {
                return ResourceManager.GetString("BannerOverlay_TopPriorityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Count.
        /// </summary>
        internal static string BannerOverlay_WarningCount {
            get {
                return ResourceManager.GetString("BannerOverlay_WarningCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Text.
        /// </summary>
        internal static string BannerOverlay_WarningText {
            get {
                return ResourceManager.GetString("BannerOverlay_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist Settings.
        /// </summary>
        internal static string Blacklist_Button {
            get {
                return ResourceManager.GetString("Blacklist_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        internal static string Blacklist_Label {
            get {
                return ResourceManager.GetString("Blacklist_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Mage.
        /// </summary>
        internal static string BlueMage_Label {
            get {
                return ResourceManager.GetString("BlueMage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mighty Guard Missing.
        /// </summary>
        internal static string BlueMage_MightyGuard {
            get {
                return ResourceManager.GetString("BlueMage_MightyGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mighty Guard.
        /// </summary>
        internal static string BlueMage_MightyGuardLabel {
            get {
                return ResourceManager.GetString("BlueMage_MightyGuardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetherial Mimicry Missing.
        /// </summary>
        internal static string BlueMage_Mimicry {
            get {
                return ResourceManager.GetString("BlueMage_Mimicry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetherial Mimicry.
        /// </summary>
        internal static string BlueMage_MimicryLabel {
            get {
                return ResourceManager.GetString("BlueMage_MimicryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocobo.
        /// </summary>
        internal static string Chocobo_Label {
            get {
                return ResourceManager.GetString("Chocobo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocobo Missing.
        /// </summary>
        internal static string Chocobo_WarningText {
            get {
                return ResourceManager.GetString("Chocobo_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables {0} Warning.
        /// </summary>
        internal static string Commands_DisablesModule {
            get {
                return ResourceManager.GetString("Commands_DisablesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling {0} Warning.
        /// </summary>
        internal static string Commands_DisablingModule {
            get {
                return ResourceManager.GetString("Commands_DisablingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables {0} Warning.
        /// </summary>
        internal static string Commands_EnablesModule {
            get {
                return ResourceManager.GetString("Commands_EnablesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling {0} Warning.
        /// </summary>
        internal static string Commands_EnablingModule {
            get {
                return ResourceManager.GetString("Commands_EnablingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles {0} Warning.
        /// </summary>
        internal static string Commands_TogglesModule {
            get {
                return ResourceManager.GetString("Commands_TogglesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Options.
        /// </summary>
        internal static string Common_AdditionalOptions {
            get {
                return ResourceManager.GetString("Common_AdditionalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Common_Command {
            get {
                return ResourceManager.GetString("Common_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duties Only.
        /// </summary>
        internal static string Configuration_DutiesOnly {
            get {
                return ResourceManager.GetString("Configuration_DutiesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will only show warnings while you are in a duty
        ///When disabled will show warnings everywhere.
        /// </summary>
        internal static string Configuration_DutiesOnlyHelp {
            get {
                return ResourceManager.GetString("Configuration_DutiesOnlyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Sanctuaries.
        /// </summary>
        internal static string Configuration_HideInSanctuary {
            get {
                return ResourceManager.GetString("Configuration_HideInSanctuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Mode.
        /// </summary>
        internal static string Configuration_PreviewMode {
            get {
                return ResourceManager.GetString("Configuration_PreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled will only evaluate warnings for you.
        /// </summary>
        internal static string Configuration_SoloModeHelp {
            get {
                return ResourceManager.GetString("Configuration_SoloModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutscene.
        /// </summary>
        internal static string Cutscene_Label {
            get {
                return ResourceManager.GetString("Cutscene_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Cutscene.
        /// </summary>
        internal static string Cutscene_WarningText {
            get {
                return ResourceManager.GetString("Cutscene_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancer.
        /// </summary>
        internal static string Dancer_Label {
            get {
                return ResourceManager.GetString("Dancer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Partner Missing.
        /// </summary>
        internal static string Dancer_WarningText {
            get {
                return ResourceManager.GetString("Dancer_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Partner.
        /// </summary>
        internal static string Dancer_WarningTextShort {
            get {
                return ResourceManager.GetString("Dancer_WarningTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Warning Time.
        /// </summary>
        internal static string Food_EarlyWarningLabel {
            get {
                return ResourceManager.GetString("Food_EarlyWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Filter.
        /// </summary>
        internal static string Food_EnableFilter {
            get {
                return ResourceManager.GetString("Food_EnableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food_Label {
            get {
                return ResourceManager.GetString("Food_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress in Combat.
        /// </summary>
        internal static string Food_SuppressInCombat {
            get {
                return ResourceManager.GetString("Food_SuppressInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Missing.
        /// </summary>
        internal static string Food_WarningText {
            get {
                return ResourceManager.GetString("Food_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Filters.
        /// </summary>
        internal static string Food_ZoneFilters {
            get {
                return ResourceManager.GetString("Food_ZoneFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display warning only in the following zones.
        /// </summary>
        internal static string Food_ZoneFiltersDescription {
            get {
                return ResourceManager.GetString("Food_ZoneFiltersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string FreeCompany_Any {
            get {
                return ResourceManager.GetString("FreeCompany_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff Count.
        /// </summary>
        internal static string FreeCompany_BuffCount {
            get {
                return ResourceManager.GetString("FreeCompany_BuffCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff Selection.
        /// </summary>
        internal static string FreeCompany_BuffSelection {
            get {
                return ResourceManager.GetString("FreeCompany_BuffSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company.
        /// </summary>
        internal static string FreeCompany_Label {
            get {
                return ResourceManager.GetString("FreeCompany_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific.
        /// </summary>
        internal static string FreeCompany_Specific {
            get {
                return ResourceManager.GetString("FreeCompany_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeCompany Buff Missing.
        /// </summary>
        internal static string FreeCompany_WarningText {
            get {
                return ResourceManager.GetString("FreeCompany_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeCompany Buff.
        /// </summary>
        internal static string FreeCompany_WarningTextShort {
            get {
                return ResourceManager.GetString("FreeCompany_WarningTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterion.
        /// </summary>
        internal static string Labels_Criterion {
            get {
                return ResourceManager.GetString("Labels_Criterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Labels_Default {
            get {
                return ResourceManager.GetString("Labels_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Labels_Disabled {
            get {
                return ResourceManager.GetString("Labels_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Options.
        /// </summary>
        internal static string Labels_DisplayOptions {
            get {
                return ResourceManager.GetString("Labels_DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Labels_Enabled {
            get {
                return ResourceManager.GetString("Labels_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme &amp; Unreal.
        /// </summary>
        internal static string Labels_ExtremeUnreal {
            get {
                return ResourceManager.GetString("Labels_ExtremeUnreal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Select.
        /// </summary>
        internal static string Labels_ModeSelect {
            get {
                return ResourceManager.GetString("Labels_ModeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Labels_Options {
            get {
                return ResourceManager.GetString("Labels_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Labels_Priority {
            get {
                return ResourceManager.GetString("Labels_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savage.
        /// </summary>
        internal static string Labels_Savage {
            get {
                return ResourceManager.GetString("Labels_Savage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Labels_Scale {
            get {
                return ResourceManager.GetString("Labels_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Labels_Seconds {
            get {
                return ResourceManager.GetString("Labels_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate.
        /// </summary>
        internal static string Labels_Ultimate {
            get {
                return ResourceManager.GetString("Labels_Ultimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        internal static string Labels_Unset {
            get {
                return ResourceManager.GetString("Labels_Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string Labels_Warnings {
            get {
                return ResourceManager.GetString("Labels_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Options.
        /// </summary>
        internal static string PartyOverlay_ColorOptions {
            get {
                return ResourceManager.GetString("PartyOverlay_ColorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Frame Overlay Configuration.
        /// </summary>
        internal static string PartyOverlay_ConfigurationLabel {
            get {
                return ResourceManager.GetString("PartyOverlay_ConfigurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing Effects.
        /// </summary>
        internal static string PartyOverlay_FlashingEffects {
            get {
                return ResourceManager.GetString("PartyOverlay_FlashingEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Icon.
        /// </summary>
        internal static string PartyOverlay_JobIcon {
            get {
                return ResourceManager.GetString("PartyOverlay_JobIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Frame Overlay.
        /// </summary>
        internal static string PartyOverlay_Label {
            get {
                return ResourceManager.GetString("PartyOverlay_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string PartyOverlay_PlayerName {
            get {
                return ResourceManager.GetString("PartyOverlay_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Outline.
        /// </summary>
        internal static string PartyOverlay_WarningOutlineColor {
            get {
                return ResourceManager.GetString("PartyOverlay_WarningOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Text.
        /// </summary>
        internal static string PartyOverlay_WarningText {
            get {
                return ResourceManager.GetString("PartyOverlay_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage.
        /// </summary>
        internal static string Sage_Label {
            get {
                return ResourceManager.GetString("Sage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kardia Partner Missing.
        /// </summary>
        internal static string Sage_WarningText {
            get {
                return ResourceManager.GetString("Sage_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kardia Partner.
        /// </summary>
        internal static string Sage_WarningTextShort {
            get {
                return ResourceManager.GetString("Sage_WarningTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        internal static string Scholar_Label {
            get {
                return ResourceManager.GetString("Scholar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faerie Summon Missing.
        /// </summary>
        internal static string Scholar_WarningText {
            get {
                return ResourceManager.GetString("Scholar_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faerie Summon.
        /// </summary>
        internal static string Scholar_WarningTextShort {
            get {
                return ResourceManager.GetString("Scholar_WarningTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritbond.
        /// </summary>
        internal static string SpiritBond_Label {
            get {
                return ResourceManager.GetString("SpiritBond_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritbond Missing.
        /// </summary>
        internal static string SpiritBond_WarningText {
            get {
                return ResourceManager.GetString("SpiritBond_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner.
        /// </summary>
        internal static string Summoner_Label {
            get {
                return ResourceManager.GetString("Summoner_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Summon Missing.
        /// </summary>
        internal static string Summoner_WarningText {
            get {
                return ResourceManager.GetString("Summoner_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Summon.
        /// </summary>
        internal static string Summoner_WarningTextShort {
            get {
                return ResourceManager.GetString("Summoner_WarningTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Tabs_Settings {
            get {
                return ResourceManager.GetString("Tabs_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Alliance Members.
        /// </summary>
        internal static string Tank_CheckAllianceStances {
            get {
                return ResourceManager.GetString("Tank_CheckAllianceStances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable in Alliance Raid.
        /// </summary>
        internal static string Tank_DisableInAllianceRaid {
            get {
                return ResourceManager.GetString("Tank_DisableInAllianceRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanks.
        /// </summary>
        internal static string Tank_Label {
            get {
                return ResourceManager.GetString("Tank_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Stance Missing.
        /// </summary>
        internal static string Tank_WarningText {
            get {
                return ResourceManager.GetString("Tank_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Stance.
        /// </summary>
        internal static string Tank_WarningTextShort {
            get {
                return ResourceManager.GetString("Tank_WarningTextShort", resourceCulture);
            }
        }
    }
}
